### ISSUE TITLE
in-house model

### ISSUE THREAD

**Issue by oneuni01** [SHI-Labs/Prompt-Free-Diffusion#18]
Hi, interesting work!

if I'm missing or not but I've found the in-house model yet, 
any plan to release it? since the in-house model is matched with the SeeCoders.

Thanks!

**Comment by xingqian2018** [comment]
I am afraid that our in-house model needs to be kept private. But SeeCoder is usable and as well finetune-able to any opensource UNet diffuser so it should not stop any training / inference activity.
