### ISSUE TITLE
VTON examples

### ISSUE THREAD

**Issue by ParadiseN1** [SHI-Labs/Prompt-Free-Diffusion#19]
Hi, thank you for your amazing work! I'm trying to reproduce your VTON example from the paper, but I couldn't get how you get those. I've tried this:
1. T-shirt image on white background (from store) -> SeeCoder
2. Mask of upper body human t-shirt  with different preprocessor (for segmentation I used (150, 5, 61) color which corresponds to human)

Please could you point me, to what I am missing?

Thank you!

**Comment by Deepak2405** [comment]
hi, were you able to produce results?
