### ISSUE TITLE
Virtual Try-On testing on demo

### ISSUE THREAD

**Issue by carvychen** [SHI-Labs/Prompt-Free-Diffusion#3]
Hi, thank you for your great work.

How to test the cases of virtual try-on with your demo where only one control input, but at least there are two conditions, e.g., cloth mask and garment image?

**Comment by xingqian2018** [comment]
We have yet to release that part. A rough pipeline: a) uses segmentation to get cloth masks, b) gets the canny edge of the model, c) seecoder + ControlNet, gets a new image, d) combines new images and original image based on the mask.

**Comment by Vking1** [comment]
Hello, thank you for providing the code, but I am currently prompted with torch. cuda. OutOfMemoryError: CUDA out of memory when starting. The details are as follows: torch. cuda. OutOfMemoryError: CUDA out of memory Tried to allocate 4.50 GiB (GPU 0; 4.00 GiB total capacity; 3.16 GiB already allocated; 0 bytes free; 3.40 GiB reserved in total by PyTorch) If reserved memory is>>allocated memory try setting max_ Split_ Size_ Mb to avoid fragmentation See documentation for Memory Management and PYTORCH_ CUDA_ ALLOC_ CONF. How to solve it?

**Comment by xasd2003** [comment]
> We have yet to release that part. A rough pipeline: a) uses segmentation to get cloth masks, b) gets the canny edge of the model, c) seecoder + ControlNet, gets a new image, d) combines new images and original image based on the mask.

Hello, thank you for your great work. 
I'm not sure if the demo we use following your pipeline b) and c).The result looks not so good. Should we use the realistic sd model like koreandoll?  In addition, the canny edge of the ControlNet preprocess seems to have some influence。

![image](https://github.com/SHI-Labs/Prompt-Free-Diffusion/assets/11574772/a3731c78-06c3-483e-8d96-d5ad73e6c11d)

**Comment by vtddggg** [comment]
It looks that we should modify the ControlNet to inpainting, like https://github.com/mikonvergence/ControlNetInpaint
Do not know how difficult is it to adapt the code.

**Comment by xingqian2018** [comment]
> > We have yet to release that part. A rough pipeline: a) uses segmentation to get cloth masks, b) gets the canny edge of the model, c) seecoder + ControlNet, gets a new image, d) combines new images and original image based on the mask.
> 
> Hello, thank you for your great work. I'm not sure if the demo we use following your pipeline b) and c).The result looks not so good. Should we use the realistic sd model like koreandoll? In addition, the canny edge of the ControlNet preprocess seems to have some influence，should we get canny by hand？
> 
> ![image](https://user-images.githubusercontent.com/11574772/242150566-a3731c78-06c3-483e-8d96-d5ad73e6c11d.png)

Please check the canny edge; Looks like these texture-edges dominate, which is the expected behavior. Also you need d) copy the face and other parts of the image into the generated image. (Inpainting maybe a more desirable approach)
