### ISSUE TITLE
[Question] Pre-computed unconditional embeddings

### ISSUE THREAD

**Issue by BlenderNeko** [SHI-Labs/Prompt-Free-Diffusion#4]
I noticed that the assets folder contains some pre-computed embeddings that function as the unconditional input. Were these computed similarly to how the graido app uses black images to provide the unconditional embedding?

**Comment by xingqian2018** [comment]
Although we provide assets/clip_ug.pth, we didn't actually use that. The UG for prompt-free diffusion is all zeros vectors.
But prompt-free is totally fine with traditional UG (i.e. negative prompts), you may try use it. Our experience shows little improvement. 

The anime app, however, assets/anime_ug.pth provided improvement in results, so we apply that in the app.
