### ISSUE TITLE
anime results is strange 

### ISSUE THREAD

**Issue by ajundo** [SHI-Labs/Prompt-Free-Diffusion#7]
![image](https://github.com/SHI-Labs/Prompt-Free-Diffusion/assets/11242862/874f59d4-cc96-4072-aa70-dbf7d5ac58d3)

I crop part of the example image as input without other modification, the result becomes very strange. Any idea?

**Comment by xingqian2018** [comment]
The anime model is experimental because we use fixed resolution narrow domain images in training, which are 512x768 portraits only. Thus performance may degrade when other resolutions and other domain images are used.
